M48
; DRILL file {KiCad (7.0.0)} date Sun Nov 19 11:36:44 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-19T11:36:44-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X123.99Y-64.22
X129.77Y-64.22
T2
X122.05Y-40.3
X122.05Y-42.8
X127.05Y-47.8
X132.05Y-40.3
X132.05Y-42.8
T0
M30
